### ISSUE TITLE
Preliquibase with kubernetes

### ISSUE THREAD

**Issue by ascjke** [lbruun/Pre-Liquibase#23]
How can I apply preliquibase on kubernetes? I see that script "CREATE SCHEMA IF NOT EXISTS ${spring.liquibase.default-schema};" doesn't executed.

**Comment by tobidope** [comment]
That has nothing to do with kubernetes and everything with your properties and/or environment variables.

**Comment by lbruun** [comment]
Closing this as it is out of scope for this project.
